### ISSUE TITLE
Companion Rules not working

### ISSUE THREAD

**Issue by synkarius** [synkarius/Caster#11]
Found by @kendonB.

1) The companion rules for core rules are not enabled by default like the core rules are.
2) The mechanism to enable companion rules doesn't work correctly.

May want to reconsider how companion rules get enabled. If nothing else better, go back to a variant of the old system.

**Comment by kendonB** [comment]
This is still not working correctly for me. To reproduce:

1. Delete my old `.caster`
2. Delete any lingering pyc using `find . -name "*.pyc" -type f -delete`
3. Unregister and reregister Natlink
4. Make sure I'm on the latest `ccrmerger2` branch
5. Start Dragon
6. Say "Enable Navigation Companion" or "Enable Python", or "Enable R"

All three result in just the dictation showing and the enabling command not being executed.

**Comment by kendonB** [comment]
OK this does work:

1. Delete my old `.caster`
2. Delete any lingering pyc using `find . -name "*.pyc" -type f -delete`
3. Unregister and reregister Natlink
4. Make sure I'm on the latest `ccrmerger2` branch
5. Start Dragon
6. Reboot Dragon once started
7. Say "Enable Navigation Companion" or "Enable Python", or "Enable R"

So it looks like the system needs to reboot twice the first time for this to work. However, I still think it might be intermittent because I came here after testing with Navigation Companion working fine for some time. Then I went to do some R coding and found that the Rlang rule wasn't working. Then I started trying to reproduce using the ccrmerger2 branch (rather than my copy) and found the above. I will let you know if I notice any problems again.
