### ISSUE TITLE
Issues with Windows 10 + DNS 14

### ISSUE THREAD

**Issue by tbenst** [synkarius/caster#145]
I have a clean install of natlink, DNS 14 and Caster on Windows 10. I am trying the commands in Quick Reference with variable success. Any tips on troubleshooting? I have the natlink debugging turned on and set "debug_speak": true although this didn't seem to do anything.

Numbers (1): works
alphabet, punctuation, spacing (2): works
comparisons (3): works

Selection, Editing (4): all work except shin, queue & fly

text formatting commands (5): none working

Programming core (6): none working ( tested in sublime text 3 )

Mouse replacement (7): all working

template-based navigation (8): none working

window management (9): all working except dredge (dragon does not realize it is a command)

Thanks!

**Comment by synkarius** [comment]
"dredge" and the template-based commands were under construction for a while and their new modes were never fully completed. I forgot about that. The old versions should be restored until and unless the new versions get completed. I'll put those back in some time this week if not tomorrow.

As for (4) and (5), that's very strange. So, commands like "shackle" and "duple" work, but "shin" and "queue" don't? Can you test "shackle" and "duple" for me if you haven't already?

Regarding (8), have you enabled a language? None are enabled by default. Try saying "enabled Javascript" and then try again.

**Comment by tbenst** [comment]
Ah thanks! 5 was user error--I neglected to say bow.  Although powerful, I will likely turn this off as I don't see myself using the combination often if ever. Perhaps add to the pdf an example command? "snake bow some words"

Shackle and duple work. I tried saying "fly arch" and "shin foxy". Both are recognized correctly and marked as commands, but 'a' and 'f' are printed respectively.

And yep, 6 was user error again. Perhaps add a line to the pdf noting that "enable Python | JavaScript | ..." Must be said?

**Comment by synkarius** [comment]
Whoops, meant to make that a "refs", not a "fixes". 

I asked about "duple" and "fly" because they're in the same file as "shin" and "queue". Trying to eliminate possibilities. When you're using shin/queue/fly, you're not in an empty document, right? I'm quite puzzled by this one, but I'm sure we can figure it out.

**Comment by chilimangoes** [comment]
Could the shin/queue/fly issue be a misinterpretation of what those commands are supposed to do? I ask because although valid, the combinations "fly arch" and "shin foxy" sound kind of like you might be expecting them to output Ctrl+a and Shift+f respectively. What they should do is "Ctrl+RightArrow followed by the letter a" and "Shift+RightArrow followed by the letter f" respectively. Which is probably why @synkarius asked if you weren't in an empty document. If you are, or if you're at the end of the document, you wouldn't see any effect from shin or fly.

**Comment by tbenst** [comment]
@chilimangoes yep you are correct, I misunderstood what those commands are supposed to do. 

Are you aware of any scripts floating around that allow for control + arbitrary key? Happy to create it and share if not, but I'm guessing someone has had this thought before ;)

**Comment by chilimangoes** [comment]
Dragon has the built in ability to do arbitrary key combinations. Just say "press control a" for example. :)

**Comment by tbenst** [comment]
Sweet! Thanks for all the help.
