### ISSUE TITLE
Programming core commands not working in Eclipse

### ISSUE THREAD

**Issue by findausername** [synkarius/caster#156]
I enabled the programming core commands (e.g. to create a for loop) and they work well using Notepad++, but in Eclipse they are not working. Do I have to change the settings to solve this problem?

btw: Thanks to synkarius for the quick and helpful answer concerning my last issue.

**Comment by Versatilus** [comment]
This is often an issue with user permissions. If Eclipse is being run as
administrator, then caster may not have permission to send keystrokes to
that window. My personal ugly workaround was to completely disable UAC and
run as an administrator. There was talk at one point of creating a proxy
application to get around this restriction, but I've been out of the loop
for almost a year and I have no idea where that idea went.

**Comment by synkarius** [comment]
This is due to a problem with the CCR Merger being unable to correctly merge contexted MergeRules. I've known about it for a while and haven't gotten around to fixing it. For now, https://github.com/synkarius/caster/commit/475485f15d3727a6f429727add2068236faa81db will make the symptoms go away. Get the latest version of Develop branch.

**Comment by findausername** [comment]
Thanks for the quick response. Using the development branch it works.
Unfortunately, there was another problem that I cannot replicate currently:  The system clipboard wasn't working (via CTRL+C / V).

**Comment by synkarius** [comment]
@findausername I forgot to say re: #155, you're welcome. :)

Hard to help with the clipboard bug though if you can't reproduce...
