### ISSUE TITLE
can import dragonfly but not dragonfly.grammer

### ISSUE THREAD

**Issue by partially-applied** [synkarius/caster#165]
I am trying to install caster. 

The debug messages are wonderful for natLink - thanks for whoever did it 👍 

![dragon_error](https://cloud.githubusercontent.com/assets/20347647/20798053/ab1fa308-b807-11e6-942a-4e40f6e237d5.png)

I am stuck trying to import grammar.

**Comment by partially-applied** [comment]
... after a while ... 

- python `import dragonfly.grammer` still does not work from terminal :( 

- Error `C file access` still happens

BUT natlink does not show any more errors :( I am not sure if its a good thing or bad thing. 

![dragon_error](https://cloud.githubusercontent.com/assets/20347647/20803381/30227fce-b819-11e6-83db-226094512dc4.png)

Testing caster commands after opening dragonSpeak does not seem to work :( is there a hello world I can try.

**Comment by chilimangoes** [comment]
Hi @partially-applied,

Some of the errors you mention are a bit cryptic, but might be related to how/whether you have Dragonfly installed. However, first things first. Based on your NatLink debug window screenshot, I think the reason why Caster isn't loading is because of the way you have your UserDirectory set up. For comparison, here's what my folder structure looks like.

![natlink_userdirectory](https://cloud.githubusercontent.com/assets/1724779/20814478/9c7fb27c-b7ce-11e6-948c-6bc6fb01d223.png)

And in the NatLink configuration UI, my UserDirectory setting points to `C:\NatLink\UserGrammars\` rather than `C:\NatLink\UserGrammars\caster\` (or `C:\caster\caster` in your case). Without seeing the rest of your directory structure, I think that pointing your UserDirectory to `C:\caster\` instead of `C:\caster\caster\` should fix the immediate problem Caster not being loaded when NatLink starts up. (You should see a message in the NatLink window saying something to the effect of `*- Starting Caster v 0.5.3 -*`)

If Dragonfly isn't installed correctly, you may get some new errors in the NatLink debug window, but let's tackle one thing at a time.

On a related note, I would recommend setting up your UserDirectory more like how I've done it, and copy or link the `_caster.py` file and `caster` folder into the UserDirectory, rather than pointing your UserDirectory to where you downloaded Caster. The reason being that you may want to add additional grammars later on, and that would get kind of messy with the way you have it set up. The UserDirectory is meant to be where you put *all* user grammars, it's not just for Caster.

**Comment by partially-applied** [comment]
hey @chilimangoes  ! 

Thanks A lot for your help, I did what you asked me to do. 

For now and messages while starting dragon does not appear 

However when I a command like clamour nothing happened :( ( as in it "clamour" gets written - not "!")

It's difficult to say because of a lack of training or a bad microphone.

![dragon_error](https://cloud.githubusercontent.com/assets/20347647/20833878/0a1ec1b8-b8bc-11e6-94c3-9f8ad799d70c.png)

For now I get the callback messages. 

Thanks a lot for your help ! - I really appreciate it since I have been suffering from severe RSI :(

**Comment by partially-applied** [comment]
Actually the error still persists :( 

![dragon_error](https://cloud.githubusercontent.com/assets/20347647/20835277/e159e94e-b8c3-11e6-88fa-d97ab60421b1.png)

**Comment by partially-applied** [comment]
... 

Okay, So I got caster showing up in the debug window :D 

It seems there is a separate error ( Progress ? ) 

![dragon_error](https://cloud.githubusercontent.com/assets/20347647/20836103/058ad1ee-b8c8-11e6-980d-2bec2059ef84.png)

**Comment by partially-applied** [comment]
If you look at the above error message. it has something to do with me having deleted C:/Caster 

After restoring C:/Caster ( not changing the UserDirectory in NatLink ) 

I still get the same import error.

![dragon_error1](https://cloud.githubusercontent.com/assets/20347647/20836484/bc7b6aa2-b8c9-11e6-85b3-e573d6e845ac.png)
![dragon_error](https://cloud.githubusercontent.com/assets/20347647/20836491/c281deae-b8c9-11e6-9e2c-5c1c84c76110.png)

**Comment by partially-applied** [comment]
The issue is resolved. 

- It had to do with installing dragonfly incorrectly. 

- do not use the .exe file. 

- use github zip. 

best wishes and thanks
