### ISSUE TITLE
 CCR not working in Rstudio

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#167]
Any idea why this might be? I have this working in every other app I've tried, including Microsoft Word.

**Comment by Versatilus** [comment]
I have no personal experience with this, but usually this sort of thing
where an application isn't working at all for me has been due to
permissions such as running as administrator or not..

**Comment by chilimangoes** [comment]
I just downloaded the latest version of RStudio and CCR seems to work fine for me. Like @Versatilus mentioned, if the application is being run with administrator rights or anything like that, Dragon will be completely unable to interact with it.

Do a quick test to see if the problem is specifically with Caster CCR commands or Dragon in general. With the focus on the RStudio window, say "press alt F", which should open the File menu. With the focus on the Console pane in RStudio, you can also try dictating some text, like "this is a test". Assuming you have a recent version of Dragon NaturallySpeaking, and assuming default settings, you should see a dictation box with the text that you just dictated in it since RStudio isn't a natively supported app. Say "click transfer" or click the Transfer button and see if the text that you just dictated appears in the Console pane.

**Comment by kendonB** [comment]
yes, this was because I was running as administrator. It is working fine now.
