### ISSUE TITLE
transformers example?

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#17]
Would be good to get a full example file (not words.txt) to place into .caster/transformers folder to test it out? We could even put something in there by default that, for example, transforms the Python rule with something benign like "long not" -> "long knot".

**Comment by synkarius** [comment]
So, having examples is a great idea, but they should go in the docs, not the source. Anything that goes in the source will get picked up by Caster's scan now.

**Comment by synkarius** [comment]
This is a good idea. Just make sure you comment out the `get_transformer` function at the bottom or it will get picked up by Caster's scan. 

Also, perhaps this should go in the docs and not be an automatic thing that happens with Caster?

Also also, this might not be the best place to put ideas for features. I doubt anyone will be coming to my fork rather than the main repo in the future.
