### ISSUE TITLE
Settings.py initialized more than once

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/Caster#21]
During startup Caster prints out the following three times.
`Caster User Directory: C:/Users/Main/.caster`

Looks like `settings.initialize()` not only from `settings.py` but is being called from `Grids.py` and `Legion.py` which makes a total of three calls.

So `settings.initialize()` is because the GUI windows need castervoice on the Python path?

**Comment by synkarius** [comment]
That is mostly correct. I added `settings.initialize()` because there was no way to import `settings` without running all the init code, and thus no way to mock it in unit tests. Now settings can be mocked pretty easily in unit tests, which has been and should continue to be _extremely_ useful.

Nothing should be importing grids.py or legion.py though, so it shouldn't be getting called multiple times unless someone uses one of those grids... hmm.

**Comment by synkarius** [comment]
Okay, or so I thought. It turns out that stuff is in fact importing those files. Stopping that is the fix here.

**Comment by LexiconCode** [comment]
Resolved
