### ISSUE TITLE
Enabling/Disabling of grammars commands are not available with caster first boot.

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/Caster#25]
Enabling or `disabling alias/chain alias` or any grammar like Firefox are not available as commands with first boot (when Caster configuration files are first generated). The commands simply print out text. If Dragon is restarted for a second time they are recognized as commands.

**Comment by LexiconCode** [comment]
Steps to reproduce the issue.
1. Delete `.caster\data`
2. Then start Dragon. Enable/disable command should not work.
3. Restart Dragon. Enable disabled mansion work as expected.

**Comment by kendonB** [comment]
I am finding this same problem after adding a user rule as well. "enable navigation user" isn't available first boot after installing it in `.caster/rules`. In that case, however, it also doesn't work after a second boot. I will file a separate issue for the latter problem.

**Comment by LexiconCode** [comment]
is that a custom rule or a caster core navigation rule moved into `.caster/rules`?

**Comment by kendonB** [comment]
Custom rule

**Comment by synkarius** [comment]
This bug is a leftover from when I switched the default loaded boolean for newly recognized rules from False to True. All rules are newly recognized on first boot, but the core rules' names are hardcoded in, so that's what were being allowed to load on first boot: the core rules.

I have tested both @LexiconCode's and @kendonB's scenarios.
