### ISSUE TITLE
Partial Aenea + Caster support

### ISSUE THREAD

**Issue by Danesprite** [synkarius/caster#312]
[Aenea](https://github.com/dictation-toolbox/aenea) is a client-server library for using voice macros from Dragon NaturallySpeaking and Dragonfly on remote/non-windows hosts (Linux X11 or MacOS).

I noticed that allowing Aenea's `Key`, `Text` and `Mouse` proxy action classes to be used instead of the classes from dragonfly has been [mentioned before](https://gitter.im/synkarius/caster?at=57a51b37978997001e9a27c6) on the Caster Gitter channel by @tbenst.

I think a good approach would be to have a Caster setting in the miscellaneous section for conditional importing of those classes from dragonfly or aenea and replacing relevant import statements in caster with something like `from caster import Key` to keep things clean. Perhaps `aenea.ProxyAppContext` could be imported as `AppContext` too? I'm not sure.

I use Aenea extensively with my own grammars, so I'm happy to implement this and test it. Of course, Caster features such as the mouse grids would not work server-side.

**Comment by tbenst** [comment]
Hey, happy to help with this. I still use this setup pretty frequently but have fallen off of master on aenea and caster. The main approach I took was to take caster files and then call the comparable aenea functions instead. Take a look at ccrmerger, mergerule and nexus in the link below:

https://github.com/tbenst/magneto-client/tree/master/magneto

**Comment by Danesprite** [comment]
Hey, thanks for the links! I will try using your approach. That app indicator sounds like a good idea 👍

**Comment by esc123** [comment]
Sorry, don't have anything of much use to add but just want to give a +1 for this idea. It would make life for me so much easier if it were possible to use Casters functionality in a Linux environment. If making the adjustments to Caster that you suggest @Danesprite would make that possible I for one would be extremely happy. Windows is the devil! :)

**Comment by Danesprite** [comment]
I have this implemented in my fork now (https://github.com/Danesprite/caster/commit/9685f0bc2662fad76182111f901b88d63a99d9d6). It seems to work nicely with Caster's Emacs and Firefox grammars at least. Will make a pull request tomorrow.

Let me know if I've messed up somewhere; there are quite a few similar changes.

**Comment by esc123** [comment]
Awesome news. I haven't attempted to install Aenea yet because of its non-compatibility with caster so I will attempt to install that first. I hear it's rather tricky so may take a while. But when I do Ill let you know if your changes have been successful. Thanks!

**Comment by tbenst** [comment]
Nice work!  One other piece of integration between Caster and aenea that’s been critical to my workflow is on-the-fly addition of commands. An example of this is in  https://github.com/tbenst/magneto-client/blob/master/magneto/modules/core/copypaste.py, which shows a simple method for creating a copy-paste dictionary. Eg if I say right now “con arch copy comment”  that would execute control-a, control-c on host, and  send the contents of the clipboard back to caster on guest. Caster would then save the string under the key “comment” in a dictionary (And save to disk) so that later I could say “paste comment” and the keystrokes would be executed. This technique is also potentially applicable for creating macros on the fly without restarting dragon.  My copy paste dictionary has a couple hundred entries in it, and way easier than a keyboard ;)

**Comment by Danesprite** [comment]
@tbenst Thanks! That's a clever way of using the clipboard! I'll try that out and see if I can add it in.
