### ISSUE TITLE
Browser plug-ins which communicate with Dragon

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#32]
I basically want to replace the plug-ins that come with Dragon 13, since Dragon 13 is terrible.

**Comment by synkarius** [comment]
https://developer.chrome.com/extensions/xhr

**Comment by Versatilus** [comment]
I'm currently using NaturallySpeaking 13 Home, and I definitely regret not getting Premium. What makes version 13 so terrible? I'm primarily asking because, thanks to the generosity of others using GoFundMe, I'll be upgrading soon to a very high-end laptop and I was wondering whether I should try to find a copy of 12.5 Premium, or go with 13 Premium. I hope that with a fast enough system. I might be able to use BestMatch V in Dragon 13 effectively.

Because I have no use of my arms, I make extensive use of the browser plug-in for dictation in places like here, Facebook, and email. I've thought about switching to 12.5 Premium and trying to do what you're suggesting here, but I recently had a thought about the .5 releases of the Dragon products. I'm a little hesitant of investing time and energy into this sort of project, and then seeing Nuance release a NaturallySpeaking 13.5 a few months from now that fixes most of the people's gripes.

**Comment by synkarius** [comment]
My major gripe with 13 is that it disallowed dictation into any program without use of the dictation box. NaturallySpeaking 13 only allows free dictation and Select-and-Say in Nuance-approved applications. You can get around that by using all commands for text input, but IMO, their well-intentioned quality assurance decision was a step back in usability. If you don't mind that, the out-of-the-box accuracy improvements and removal of initial accuracy training, as well as the browser plug-ins are pretty great. 

I share your hesitation about doing a project like this, for the same reasons you mentioned. That's why this one has been on the back burner for so long.

**Comment by Zone22** [comment]
I noticed a significant difference between dns 12 and dns 13 in regards to recognition speed.  Some research into the issue suggests that dns 13 is better optimized for multi core processors.  In addition BestMatch V seems to be much improved.  That being said I'd use dns since version 9 And Nuisance typically only have one maintenance update X.X.5. The plug in brakes after one or two browser updates. It frustrates me that there's no competition for dns to innovate their product and to provide long term support. That being said it and are some real value to writing are own browser plugins. Although I question how often it will have to be updated to maintain compatibility with the rapid release cycles nearly all modern browsers have adopted?

**Comment by synkarius** [comment]
I wrote a Google Chrome plugin for something else about eight months ago. It actually hasn't required *that* much maintenance. I could probably handle creating and maintaining the Google Chrome plugin, when everything else with higher priority has been finished. It might be nice to not rely on Nuance.

**Comment by chilimangoes** [comment]
Have you considered one of the Vim-like navigation browser plugins? These would allow you to do most everything simply by mapping voice commands to Key actions.

**Comment by synkarius** [comment]
I tried Vimium a while back, and was impressed, but also annoyed that I couldn't selectively turn the keyboard shortcuts off. But now that I'm looking at it again, it seems I *can* turn any of them off if I want. Was it always that way?

Thanks for the suggestion, @chilimangoes. 

In my view, Vimium/etc. denecessitates this feature. At the very least, it does everything that the Dragon plug-ins do. If a good use case comes up for an even more powerful plug-in, we can make a new feature request. Until then, I'm closing this one.

**Comment by Zone22** [comment]
For reference, the Firefox version that's maintained.
https://addons.mozilla.org/en-US/firefox/addon/vimfx/

**Comment by j127** [comment]
I'm not sure exactly what you're looking for, but Pentadactyl is also maintained, though has to be downloaded from their site. It's probably closer to Vim than the other ones. Highly recommended if you're looking for Vim-commands in an browser.
http://5digits.org/pentadactyl/ (Use the nightly build.)
https://github.com/5digits/dactyl

**Comment by Zone22** [comment]
@j127 
Thanks for the info. Have you experienced compatibility issues?

**Comment by j127** [comment]
I haven't been able to get Caster (or even Dragonfly) working well yet. I program in Linux, so I have Ubuntu running on a virtual box inside of Windows 8. It isn't really working with Dragon. My main project doesn't run on Windows. I may have to write the code in Windows, push it to Github/Bitbucket, and then pull in the Virtualbox on each save. Not sure what to do yet.

I use Pentadactyl all the time though. It's great.

**Comment by chilimangoes** [comment]
@j127 

What I typically do when I need to write code for Linux is to run Linux in a Vagrant VM. When you have VM running under Vagrant, it will automatically share your source directory to /vagrant inside the VM. Then I can simply use my development tools on Windows to write code, and changes are automatically visible within the Linux VM.
