### ISSUE TITLE
BringMe path ends in .toml.defaults instead of .toml

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/caster#338]
The path is found in the settings.toml.

`BRINGME_DEFAULTS_PATH = "E:/NatLink/NatLink/MacroSystem/caster/bin/share/bringme.toml.defaults"`
Perhaps `defaultsbringme.toml`

**Comment by comodoro** [comment]
This file contains the defaults if no `bringme.toml` exists, then it is copied there, so it is not being used as TOML. Do as you see fit, if I had a candidate for name change (other than those in #336 ), it would be the `bin` directory (it implies binary)

**Comment by LexiconCode** [comment]
I gotta say I love the functionality of what you've done with the BringMe command. 

It might be time to move everything that has a default setting into a centralized file. That way it is clear were to include defaults as people continue to contribute.  I'll start with moving the default settings out of settings.py into a new file. Once that's implemented I'll revisit here and add your default as well.

What do you think?

**Comment by comodoro** [comment]
Well… I agree with the settings.py file containing default settings does not seem right. As for moving all settings into one huge file… I don't know. I think having a file for each module or thing, which does not affect other settings files in any way, might not be a bad idea. And having settings.py refactored accordingly. But it is just a thought, a topic for discussion:-)

As for bring me, I wanted to make a GUI similar to the existing Caster GUIs, because if you add a key, you may want to make sure that you did not mispronounce it or something( maybe it is just me), but I remember gRPC was the new thing and my attempts at making it work with Caster did not go well.

**Comment by LexiconCode** [comment]
Take a look at [gRPC](https://github.com/Danesprite/dragonfly/tree/feat/rpc) as with experimental integrated dragonfly with working examples.

**Comment by LexiconCode** [comment]
I'm going to close this issue for now. Thanks for your thoughts on the matter. Will revisit in the future as time allows.
