### ISSUE TITLE
Universal file dialog interface?

### ISSUE THREAD

**Issue by kendonB** [synkarius/caster#348]
I use the following commands (or slight variants) in some AppContexts for navigating through a file dialog box. Is there a way to make this universal? Particularly the `file list`, `navigation pane`, and `filename` specs where the number of `f6`s can vary across file dialog boxes.

```python
	"get up":                                
	    R(Key("a-up"), rdescript="RStudio: Navigate up"),
	"get back":                           
	    R(Key("a-left"), rdescript="RStudio: Navigate back"),
	"get forward":                        
	    R(Key("a-right"), rdescript="RStudio: Navigate forward"),
	"file list":                         
	    R(Key("a-d, f6, f6, f6"), rdescript="RStudio: Files list"),
	"navigation pane":                   
	    R(Key("a-d, f6, f6"), rdescript="RStudio: Navigation pane"),
	"filename":                   
	    R(Key("a-d, f6, f6, f6, f6, f6"), rdescript="RStudio: File name"),
```

**Comment by LexiconCode** [comment]
I'm a bit confused about what you are asking, so a few questions.

Are you asking for Universal Spec(command) or Action(implementation)?

spec`"navigation pane" Action `"a-d, f6, f6"` 

Alternatively are you asking for these specs to be (available everywhere) global instead of an AppContext like RStudio for dialog boxes....

Alternatively are you asking something specific about RStudio in the consistency of commands `file list, navigation pane, and filename` specs where the number of f6s can vary across file dialog boxes.
