### ISSUE TITLE
Is it intentional that transformers can act on already transformed Rules?

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#43]
I tried the following transformer:
```python
from castervoice.lib.actions import Key, Text
from castervoice.lib.merge.ccrmerging2.transformers.base_transformer import BaseRuleTransformer
from castervoice.lib.merge.state.short import R

from dragonfly import Repeat

class FileDialogueTransformer(BaseRuleTransformer):

    def __init__(self):
        print("FileDialogueTransformer activated!")

    def get_pronunciation(self):
        return "file dialogue transformer"

    def _transform(self, rule):
        rule._mapping["get up [<n>]"] = R(Key("a-up"))*Repeat(extra="n")
        rule._mapping["get back [<n>]"] = R(Key("a-left"))*Repeat(extra="n")
        rule._mapping["get forward [<n>]"] = R(Key("a-right"))*Repeat(extra="n")
        print(rule._mapping)
        del rule._mapping["up [<n>]"]
        del rule._mapping["back [<n>]"]
        del rule._mapping["forward [<n>]"]
        return rule

    def _is_applicable(self, rule):
        return rule.__class__.__name__ == "FileDialogueRule"


def get_transformer():
    return FileDialogueTransformer
```
and I ended up getting key errors once I said "enable file dialogue" as the `"up [<n>]"` entry had already been deleted. I see three solutions to this:

1. Ensure that transformers return the same rule if applied once or twice (as a validation).
2. Always reload the original rule when enabling an app rule.
3. Don't run transformers when enabling a rule - only at startup

**Comment by LexiconCode** [comment]
Whatever solution we proceed with in the future Transformers reload when edited just like other rules e.g. MappingRules.

**Comment by kendonB** [comment]
I don't see this issue when enabling other rules. I'm not sure what it is about the file dialogue rule that causes me to get the error.

**Comment by LexiconCode** [comment]
@kendonB I'll try to reproduce tomorrow.

**Comment by synkarius** [comment]
Answer to the title question: yes, it was intentional that transformers can act on already transformed rules. Maybe that was a design mistake though.

For clarity, here's what happens when you enable a rule:
1. The rule's class is used to instantiate a completely new copy of the rule.
2. The rule runs through all transformers and optionally a few other processes.
3. The rule either gets added to the CCR repeat rule (this is a simplification) or is just added to a grammar if it's a MappingRule.

As for @kendonB's solutions:
3. **This could work.** I don't really see a use case for modifying instances rather than the classes themselves. I think this is maybe* the best path forward.

@LexiconCode The point of making transformers implement `get_pronunciation` is so that you can enable/disable transformers by voice. However, if transformations only happen at boot time, there's no need for this ability.

**Let's take a moment** and discuss the elephant in the room here. Transformers are hard to use compared to just dropping modified rules into the user directory *and they don't get you much comparatively*. @LexiconCode has a vision of dynamically editing rules with transformers (formerly filter functions), *but even that could be done via the user directory*. I recommend that we cut transformers out completely and *have one mechanism instead of two* for customizations. I suggest: let's leave the words.txt one in there since it works, but deprecate and not promote the feature, and push people to just use the user directory to modify rules the same way they would coming in from the various other Dragonfly communities and even from the Vocola/Unimacro community. As the author, I feel comfortable saying that filter functions were a bad idea to begin with, and that my efforts to fix them (transformers) have failed and that I think we should cut our losses before we waste more time on this.

**Comment by LexiconCode** [comment]
All right, why not remove words text.txt as it is technical debt. I'm not sure how we can dynamically edit rules into the user directory but I'll take your word for it.

**Comment by synkarius** [comment]
@LexiconCode I would love to remove words.txt too, but isn't it a fairly commonly used feature?

As for how to dynamically edit rules in the user dir, let's think about how it would have been done with transformers. You would have needed to:

1. Create some object/process/functions, which takes a rule class or instance and then creates a UI for it, displaying specs and some representation of actions (though the actions side is pretty complex, let's just gloss over that for now).
2. Let the user change the spec and maybe even the actions in a variety of ways. You might let them do word replacement like words.txt does, or delete full commands out of rules, or even alter the actions if you're ambitious. *Steps 1 and 2 are the same whether you're using transformers or the user directory.*
3. You then have to take the changes that they've done to the rule and turn them back into generated Python code and write that to a file as a transformer in the user directory.

So the difference then would be that, instead of generating transformer python files, you'd generate rule python files back into the user directory. It's probably about equally difficulty to generate a rule vs a transformer, since a rule and a transformer have about the same amount of syntax complexity.

**Comment by LexiconCode** [comment]
The fate of transformers deserves a bit more thought especially since we've gotten this far. I'm going to sit on this for a day or two and other people's feedback is more than welcome.

**Comment by kendonB** [comment]
Removing transformers is definitely worth discussing. To frame the discussion, I think it's useful to think through the use cases and design goals the two options can handle.

First up, I don't exactly know what is meant by dynamically editing rules if not exactly what Transformers do.

In my non-promgrammer mind, the two broad options are to 1) allow people to overwrite rules directly at load time by adding a rule with the same name in the `.caster/rules` folder or 2) use transformers.

Use cases (please add to these):
1. Deleting unused commands
2. Changing actions for a given spec
3. Changing a given spec
4. Altering extras (possibly also defaults)

Design goals:
A. Have Caster rule edits easily flow through to users who have made customizations
B. Allow users to make customizations to many rules at once where appropriate
C. Minimize the maintenance load and keep the user customization system simple.

The rules option doesn't achieve A for any of the use cases.

Once we get rid of command duplication in the code (like we have for browser) then B will be easily achievable for command changes either way (1/2/3). Any extras duplication we could in principle trim out like we've done with the punctuation dict so that would achieve 4 for either option. I think we should maintain words.txt functionality until we've trimmed all of the duplication out though.

The transformers option then doesn't achieve C so the tension is between allowing for caster edits to flow through and keeping it simple. 

I'm leaning towards keeping it simple and getting rid of transformers mostly because I'm skeptical of how much a typical caster user would actually want non-bugfix edits to flow through automatically as it will mess up their system. We can also make it easier to bring changes in with a command like "merge this" which would open WinMerge and compare the user / caster files.

**Comment by kendonB** [comment]
We can also make it easier with a command like "copy <rulename> to user folder". Then I think we should actually disable auto reloading for the repo source files to discourage editing there.

**Comment by LexiconCode** [comment]
> First up, I don't exactly know what is meant by dynamically editing rules if not exactly what Transformers do.

So right now transformers load on boot. The thought was Transformers in the future could reload on edit. That way you don't have to reboot to update in transformers files.

Some further thoughts. 

My hope was that transformers would allow us to create for a higher level of abstraction. Loading rules into the user interface. You could click/voice command open up a command and edit the Command and/or Action conversely a delete Spec entirely. These edits would be saved in a toml file and the backend transformer would update the Grammars accordingly without requiring a restart of caster. All without touching a Python file.

Fundamentally this makes it much easier to create voice commands in a predictable manner through a GUI rather than an IDE. This restricts freedom but allowance will simplified workflow. The goal is to eventually make caster accessible to someone who has no programming skills yet maintain the Raw power seen in the raw dragonfly/caster syntax.

At first this would be raw dragonfly Syntax but with further work it could evolve a higher abstraction. Where individuals simply have to know keyboard shortcuts

All of what I've just described treats transformers as a framework for abstraction rather than it as a direct implementation for customizing grammars as a user facing construct.

Keep the discussion going :)

**Comment by kendonB** [comment]
Thinking into the future with these abstractions, it seems like it would be a lot easier to do validations using transformers, rather than writing new rule files. 

Say I had a GUI pop-up that allowed me to edit the action of a command and I make a mistake. With the writing rule files option, we would have to write the rule file, have caster reload it, see that there is some error, then communicate that something is wrong to the user, then re-save the old copy, all immediately after the user clicks save. Could this process happen fast enough for it not to be an issue compared to a validation that just uses a rule in memory?

**Comment by synkarius** [comment]
> With the writing rule files option, we would have to write the rule file, have caster reload it, see that there is some error, then communicate that something is wrong to the user, then re-save the old copy, all immediately after the user clicks save

I disagree. You could reuse Caster's existing validation and components (maybe in conjunction with the Dragonfly text engine if you really wanted realistic conditions) -- *inside* this GUI program you're describing. You could know if the altered rule would load in real Caster before real Caster know anything about the altered rule.

**Comment by synkarius** [comment]
Also, aside from global spec word replacements, is there any other kind of rule change you can think of which:
1. would be global and
2. wouldn't be better off as a setting or a code change?

If so, maybe you have a use case for transformers. If not, they should probably get the axe. Any non-global change is a vote for the user dir.

**Comment by synkarius** [comment]
Also, I should say, the problem about making mistakes with the GUI would also apply to transformers.

**Comment by kendonB** [comment]
I'm convinced. I'm happy to get rid of transformers. As I said earlier, I'd like to still remove all the duplication in the code before removing the words.txt functionality.

**Comment by LexiconCode** [comment]
I'm more in less agreement as well. A quick ping to @Versatilus

**Comment by synkarius** [comment]
Good. Then, if @Versatilus or anyone else has no further objections, I won't actually remove anything, but I'll prevent new transformers from being added. The words.txt transformer will remain and will continue to function.
