### ISSUE TITLE
State of TreeRule 

### ISSUE THREAD

**Issue by LexiconCode** [synkarius/Caster#44]
This issue to discuss TreeRule. Given the lines commented out `css` to load TreeRule, it's not ready yet. Therefore I've omitted the trace back.
https://github.com/synkarius/Caster/blob/02b2ffca273907651af26913bb12c3fc30e4fd7c/castervoice/lib/merge/selfmod/tree_rule/trees/css.py#L553

As an aside: This is an attempt to make a demo TreeRule. Let me know if there's anything that obviously needs to be changed for loading. When TreeRule is functional having this grammar ready will speed up testing.

```Python
from castervoice.lib.actions import Text
from castervoice.lib.const import CCRType
from castervoice.lib.ctrl.mgr.rule_details import RuleDetails
from castervoice.lib.merge.selfmod.tree_rule.tree_node import TreeNode
from castervoice.lib.merge.selfmod.tree_rule.tree_rule import TreeRule
from castervoice.lib.merge.state.actions2 import NullAction

H = TreeNode

demo_nodes = H("I say zero", Text("LevelZero"), [
            H("I say one", Text("Level One A"), [
                    H("two A one", Text("Level Two A1"), [
                            H("three A one", Text("Level Three A1")),
                            H("three A two", Text("Level Three A2")),
                            H("three A three", Text("Level Three A3"))
                        ]),
                    H("two A two", Text("Level Two A2"))
                ]),
            H("level one be", Text("Level One B")),
            H("level one see", Text("Level One C"))
    ])

class DemoTreeRule(TreeRule):
    def __init__(self):
        super(DemoTreeRule, self).__init__("demo nodes", demo_nodes)

def get_rule():
     return [DemoTreeRule, RuleDetails(ccrtype=CCRType.SELFMOD)]
```

**Comment by synkarius** [comment]
There are multiple problems here. 

1. All selfmod rules now need a config file to dump out their state when they reload. There is nothing creating those files for TreeRules at present.
2. There are a couple of logic errors in TreeRule itself.

These should both be pretty straightforward.

**Comment by synkarius** [comment]
@LexiconCode This should be good to go.

**Comment by LexiconCode** [comment]
A list of observations and questions nodes. The only thing that would be considered a bug may be the last entry.

- Can nodes be in the `.caster\rules` rule directory?

I tried loading the grammar above in the user directory and the following with the file `test.py`

`No method named 'get_rule' was found on 'test'. Did you forget to implement it?`

Therefore I tried commenting out the loading mechanism for `css.py`. Then copying the contents of `css.py` into `test.py` that resides in the user `rules` directory. When reloading Caster I get the same error message above.

- Nodes `.toml` files must be manually registered settings.toml.

Second if I load it in the tree rule `trees` directory the following error message.

```
\selfmod\tree_rule\tree_rule.py", line 25, in _get_tree_rule_config_path
    raise TreeRuleConfigurationError(msg.format(formatted_path_name))
TreeRuleConfigurationError: Path 'SM_DEMO_NODES_TREE_PATH' was not found in the 'paths' section of settings.toml. Did you add it?
```

Adding `SM_DEMO_NODES_TREE_PATH = "C:/Users/Main/.caster/data/sm_demo_tree_node.toml"` Caster starts is expected.

- is `[trees]` unused in `settings.toml`?

- How do I activate `DemoTreeRule`?

I tried saying enable `Demo Tree Rule` no effect
Adding `pronunciation = "demo tree node"` no effect.
DemoTreeRule listed  as

```
[whitelisted]
DemoTreeRule = true 
```

The only way I was able to edit was through modifying `_enabled_ordered` in ` settings.toml`

- The DemoTreeRule prints reloading to the status window each level. However it doesn't give us information on which level is loaded to inform the user on the progress levels across the node tree.

  `Reloading DemoTreeRule...`
  `DemoTreeRule reloaded.`

- A possible bug transversely Nodes on the same level?

1. "I say zero" produce "LevelZero". - expected
2. "I say "level one be" produces "Level One B". - expected
3. say "level one see" I should expect "Level One C". this is not the case only "I say zero" is only available for dictation all of the sudden. It seems as if the note reset entry command "I say zero" when I should be able to say  "level one be" and  "level one see"  producing `Level One B or C` respectively.

**Comment by synkarius** [comment]
1. If you mean to add a "nodes" python module/file separately from your custom TreeRule module, yes, it can be in the user dir. But it should be adjacent to your custom TreeRule module, so that when the path for the custom TreeRule gets added to the PYTHONPATH, it allows for the import of the adjacent module. But the much simpler/cleaner way would be to just put the tree's nodes in the same file with the rule.

2. I am able to load the rule you provided above and do not get the error you mentioned about 'get_rule' being absent.

3. Yes, new .toml files for custom TreeRules must be added to settings.toml, -- but this is not limited to TreeRules. Any selfmod rule must now have its own config file, in order to be able to dump out its state to disk when it reloads. Thinking about this, an alternate and maybe better implementation would be to have some singleton (emphatically not the Nexus) which hangs onto state for selfmod rules when they reload. It's too late for me to include this, but if selfmod rules become more popular and config files start getting out of hand, that's the solution I suggest.

4. I'm glad the error messages guided you towards correctly adding the path (which then caused the file itself to be automatically generated the next time you started Dragon).

5. I'm not sure about `[trees]`, but since I'm sure I didn't use it in the TreeRule part of the rewrite, yes probably.

6. In keeping with [old Caster's NodeRule](https://github.com/dictation-toolbox/Caster/blob/master/castervoice/lib/dfplus/hint/hintnode.py#L103), the enabling trigger for TreeRule is the spec of the root node. This seems kind of bad in hindsight though. Why have just one kind of rule with a nonstandard trigger? Making this work would be as simple as deleting `get_pronunciation` on TreeRule. I think we should do it. Do you agree?

7. There is already a hook event which provides more detailed information about node changes (NodeChangeEvent). There is just no hook which listens for it. If anyone is interested in adding that feature, take a look at the other hooks, like PrinterHook, to see how hooks work.

8. This requires some clarification. Do you agree that [this](https://ibb.co/crhWdKc) is the tree represented by the nodes in your example?

**Comment by LexiconCode** [comment]
Thanks for clarifying those points!
>     6. In keeping with old Caster's NodeRule , the enabling trigger for TreeRule is the spec of the root node. This seems kind of bad in hindsight though. Why have just one kind of rule with a nonstandard trigger? Making this work would be as simple as deleting get_pronunciation on TreeRule. I think we should do it. Do you agree?

I prefer the trigger to be the spec of the root node. However the spec is not available unless the grammar is loaded and enabled?

>     8. This requires some clarification. Do you agree that [this](https://ibb.co/crhWdKc) is the tree represented by the nodes in your example?

![Capture](https://user-images.githubusercontent.com/24551569/67820393-0866e200-fa87-11e9-9180-35dfd89a5770.JPG)

**Comment by synkarius** [comment]
Alright then (6) requires no changes. No, the enable/disable command should be available so long as the rule is loaded, not enabled and loaded.

As for (8) then, which path along that tree diagram isn't working as expected?

**Comment by LexiconCode** [comment]
OK for the context of ‘level one A B or C’. If B is recognized then should be available for C for recognition on the same node level. Instead LevelZero is only available.

**Comment by LexiconCode** [comment]
> I prefer the trigger to be the spec of the root node. However the spec is not available unless the grammar is loaded and enabled?

After experimenting for a while I think you're right. The rule name is much more intuitive than the spec itself.

**Comment by synkarius** [comment]
6) My opinion is that we should change the trigger to be consistent with all the other rules. Since you agree, I will do so.

8) NodeRule never worked in the way you are describing. When you say the spec of a node, the node's action runs and then the "active" portion of the tree changes. If you have reached one of the leaves of the tree, the active portion resets to the root of the tree. Therefore, you should not be able to say the 1B node repeatedly.

After saying 1B spec the only thing you should be able to say is the 0 spec.

**Comment by LexiconCode** [comment]
Good to clarify, I understand given that we haven't really been able to experiment until now.

**Comment by synkarius** [comment]
With that last push, TreeRule's trigger works the same as any other MergeRule's trigger. I'll leave it up to you to close out this Issue since you are the author of it.
