### ISSUE TITLE
Allow for individual key/spec clashes without knocking out entire rules?

### ISSUE THREAD

**Issue by kendonB** [synkarius/Caster#50]
Is it feasible to set up the system such that an individual spec clash between rules is handled by the enabling order without the entire rule getting knocked out? An example I just ran into was that I wanted to add the command:
```
        SymbolSpecs.COMMENT:
            R(Key("cs-c"), rdescript="RStudio: Comment"),
```
to my rstudio rule. Of course this conflicts with most language rules but this particular conflict seems like a common thing that people might do as most IDEs have a add comment or toggle comment command.

**Comment by synkarius** [comment]
Yes, it is possible. Have a look at DetailsCompatibilityChecker and its unit tests. DetailsCompatibilityChecker computes incompatibilities (and delivers that information to the merge strategy in the next step), but doesn't KO anything. In contrast, the now-used SimpleCompatibilityChecker does the opposite: KOs incompatible rules like old Caster did, but doesn't provide any information about why.

I will not add this feature, but I foresaw this request. Here is what I suggest:
1. Add a setting in the settings which re-enables DetailsCompatibilityChecker. This will get you all the incompatibility information at the merge strategy step.
2. Use the same setting to enable a new merge strategy (because as we saw, DetailsCompatibilityChecker doesn't work well with ClassicMergeStrategy). This new merge strategy can handle spec incompatibilities in some other way than a KO.

**Comment by synkarius** [comment]
Looking at it again, I forgot: DetailsCompatibilityChecker only tells you which rules are incompatible, not which specs. But that would be easy to add. Just add the incompatible specs information to the `CompatibilityResult` class. The rest of the work is already done.

Or alternatively, leave `CompatibilityResult` as it is, and deal with the incompatible rules entirely in the new merge strategy.

**Comment by kendonB** [comment]
Moved to here: https://github.com/synkarius/Caster/issues/50. Closing. Thanks!
