### ISSUE TITLE
Which Dragon version do you recommend?

### ISSUE THREAD

**Issue by RobertCorey** [synkarius/caster#52]
Hello, I just got everything up & running. I thought this library was the reason you could type directly into the text editor without the dictation box, but I googled around and I found that my issue is I'm running Dragon 13. What version do you run? thanks for the project hope i will be able to contribute once i can code again.

**Comment by synkarius** [comment]
As you've probably discovered, even if you disable the dictation box on Dragon 13, you can't dictate directly into most text editors. That said, before you switch versions, you should know that you *can* dictate into any text editor with Dragon 13 if you use commands that print what you say, rather than normal dictation. For instance, you could make a command with the spec "print <t>", then you could dictate into any window by saying the word "print" before what you meant to dictate. Dragon 13 only prevents normal dictation into nonstandard windows, not commands. This still won't let you use Select-and-Say though. 

In my experience, I program with almost 100% commands. (Even when I write comments, I usually use text formatting commands to print them, rather than turning command mode off.)

That said, I still hate Dragon 13 and run Dragon 12. 

I'm glad you like Caster, and would welcome code contributions. There is much which needs to be done.

**Comment by RobertCorey** [comment]
Thanks!
