### ISSUE TITLE
Contextually aware commands within CCR command sets

### ISSUE THREAD

**Issue by Zone22** [synkarius/caster#58]
If X command is recognized then A B C D E F  commands are only available in a language specific CCR command set. For instance HTML elements or attributes that can only be applied HTML tags within certain context. 

```
<!-- Simple video example -->
<video src="videofile.ogg" autoplay poster="posterimage.jpg">
```
<ol>
 <li>video </li>
 <li type="1">src="Text.Extension" #video attribute</li> 
 <li type="1">autoplay #video attribute</li> 
<li type="1">poster="Text.Extension" #video attribute</li> 
</ol>

The above example isn't complete but it's meant to show how commands might become available in a particular order based on the context of the previous command.

The upside with Contextually aware commands within HTML CCR command sets.
<ol>
<li type="1">A generic "close tag" command </li> 
<li type="1">Increased recognition accuracy</li> 
<li type="1">Inherently supports IDE's with auto complete enabled</li> 
<li type="1">In the long run less code to write and maintain</li>
<li type="1">Taging elements/attributes based on browser compatibility and HTML version</li>
<li type="1">Possible ability to update via an API from a website as yet to be determined</li>
<li type="1">Keeps the coder from using invalid tags or attributes</li>
</ol>

Downside
<ol>
<li type="1">At the very least require a rewrite confightml.txt and eventually other language CCR command sets</li> 
<li type="1">Most likely would require altering other aspects of Castor</li> 
</ol>

Possible Resources
https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Content_categories#Transparent_content_model

https://github.com/chajadan/DragonflyRules/blob/master/_html_lang_rules.py

**Comment by synkarius** [comment]
You and I see eye to eye on this one, Zone. All of this is technically possible right now with stuff I've been working on in the last few months. 

Your generic close tag command can be done with a ContextSeeker action which examines the context stack and the command which occurred immediately before it. (Of course, the previous command would have to be wrapped with a RegisteredAction for the ContextSeeker to see it.)

Your contextually available commands could be achieved via NodeRule, which I only got up and working a few weeks ago. Presently, it can't be incorporated into the CCR combined set, but that is the next thing I'm going to put in. Because these features are so new, I haven't documented them in any way, no YouTube no wiki. However, there are examples of ContextSeeker in dev.py, and I have a partially completed CSS NodeRule which can be activated in CCR by uncommenting this line:
https://github.com/synkarius/caster/blob/master/caster/lib/ccr.py#L115
and fixing the following line accordingly.

Furthermore, if you activate the status window by changing the settings file, the status window will give you hints as to what can come next, what just got activated by the previous command.

These are all experimental features, very new, I'm still testing them. I mention them now so that you don't have to duplicate functionality.

**Comment by synkarius** [comment]
I'm sorry, I realize this is pretty difficult with no documentation. Please feel free to ask further questions.

**Comment by Zone22** [comment]
I apologize for my lack of familiarity with your repository. I will focus on experimenting with HTML as is what I'm most comfortable with. I suppose in going about the hard way learning to code but i require a tool like Castor to even participate. Thank you for starting this project.

Will implementing NodeRule allow more commands to be nested within the 550 active commands?

**Comment by synkarius** [comment]
No need to apologize, and the HTML section is a great place for you to help out! And I'm glad you like Caster. :-)

Yes, the main purpose of NodeRule is spec reduction. It allows you to sidestep the hard limit by only having a subsection of the nested commands active at a given time. You could have thousands of commands nested in a NodeRule, with maybe only 10 or 20 in a given node.

**Comment by synkarius** [comment]
Also, I started working on incorporating NodeRule into CCR. If you create an HTML HintNode, you can add it to this array:
https://github.com/synkarius/caster/blob/master/caster/lib/dfplus/hint/_nodes.py#L16
-- and then say, "enable html", and it should be enabled with your other CCR commands. It doesn't work with the status window yet for some reason, but that's coming.

**Comment by Zone22** [comment]
I just might have to wait for documentation.

**Comment by synkarius** [comment]
https://github.com/synkarius/caster/wiki/noderule

It's up. I'm going to do the Context Stack actions (RegisteredAction, ContextSeeker, Continuer) next. You'll need ContextSeeker for your generic close tag command. I've been putting off doing the documentation because up until this point, NodeRule was buggy, and ContextSeeker wasn't complete.

**Comment by synkarius** [comment]
https://github.com/synkarius/caster/wiki/contextstack

And there's that. It's not finished, but the sections about RegisteredAction and ContextSeeker are, which is what you need. If you have further questions, I'll happily do up an example for you.

**Comment by Zone22** [comment]
if you have time a small example would be helpful in the context of HTML.

**Comment by synkarius** [comment]
Certainly. Here's how to use ContextSeeker. Let's say we have these two functions.

    def close_last_spoken(spoken):
        first = spoken[0]
        Text("</"+first+">").execute()
    def close_last_rspec(rspec):
        Text("</"+rspec+">").execute()

We commend tie them into a MappingRule like this:

    "close last tag":               ContextSeeker([L(S(["cancel"], None),
                                                     S(["html spoken"], close_last_spoken, use_spoken=True), 
                                                     S(["span", "div"], close_last_rspec, use_rspec=True))
                                                   ]),
    "html":                         R(Text("<html>"), rspec="html spoken"), 
    "divider":                      R(Text("<div>"), rspec="div"),
    "span":                         R(Text("<span>"), rspec="span"),

Notes:
* The first ContextSet in the ContextSeeker does nothing. Doing nothing is the default in this case. The first ContextSet is always the default. The default ContextSet will be executed if the next RegisteredAction spoken doesn't match any of the trigger words in any of the other ContextSets.
* `use_spoken` always returns a list of spoken words to the outcome function
* `use_rspec` always returns the rspec to the outcome function

**Comment by synkarius** [comment]
Let me know if you need any more of an example of NodeRule than [this](https://github.com/synkarius/caster/blob/master/caster/lib/dfplus/hint/nodes/css.py), though, IMO, the HTML specification doesn't really follow a tree structure unless you want to go nuts with inline attributes, and might be better off as it is as a CCR module. That said, I don't voice code HTML very much and don't really know what a workflow for that might look like, so I'll support you whichever route you take.

**Comment by Zone22** [comment]
Well it looks like I'm in for a lot of fun. It'll take me time to digest this so I can ask more structured questions.  Meantime on a slightly related note can we do the same thing with key() and mimicking command phrases? I know it's not currently implemented. 

Functionally this would allow identical keyboard shortcuts to reuse in different contexts within the same program.

**Comment by synkarius** [comment]
I'm not quite sure what you mean. Can you explain that a bit more?
