### ISSUE TITLE
Synchronizer Script + Persistent Customizer UI

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#72]
so I don't have to manually synchronize the languages every time I make a phonetic distinctness chang to one of them

- Standardized lines of CCR language modules should get ID numbers, maybe in comments

**Comment by Versatilus** [comment]
I've been giving this some thought lately, too. I've been thinking in broader terms of an expanded configuration system. I haven't worked out any specifics yet, but one thing that has bothered me from the beginning of using caster is how the way that we speak differs so that some of your wording that provides better distinctness for you is ineffective for me. It would nice to be able to change this in a configuration file instead of editing hardcoded values. 

Due to health issues I mumble a lot and some commands either don't provide enough distinctness, or get easily confused with my custom commands. "Back" for left is one that gets particularly muddled with my commands. I'm sure that a lot of this is on me and my difficulties with speech, but configuration options would help.

Ideally, I would like to fix it so that fewer specs are hardcoded. This could be as simple as initializing CCR files from defaults found in a different directory. At startup caster could notify users if the defaults are newer than their custom files.

**Comment by synkarius** [comment]
I completely understand, and I think that's a good way to let the user customize the language standard. I was talking to @Zone22 yesterday, and one of the ideas for future features that came up was a UI for customizing command sets. Maybe this could be done together with that.

**Comment by synkarius** [comment]
I'm splitting this into #98 and #99.
