### ISSUE TITLE
Enabling rules with "enable rule" command and/or manually

### ISSUE THREAD

**Issue by alexboche** [synkarius/Caster#8]
This is a loose collection of questions, observations, suggestions, none of which are all that important. 

It might be nice to have a command like "enable all rules" (especially for testing purposes) so that you don't have to say "enable…" one at a time for each rule. As you say, you could just keep a separate rules.toml file with all the rules enabled and then copied into your regular rules.toml iif you want to enable all rules but doing so requires rebooting Dragon and mmay not be as flexible if you are creating new and/or removing rules. It might aalso be cool to be able to create  profiles ( i.e. lists ) of rules which you can enable with a single command but would not necessarily be all rules e.g. "enable videogame rules " would enable all your rules related to video games. 

Is there a reason not to manually enable rules by adding them into the `_enabled_ordered` list? Besides the fact that you have to reboot Dragon in order for such changes to take effect whereas you do not have to reboot Dragon if you say "enable …"?

From David Conway,
> All MappingRules (like Acrobat, Excel, etc.) now use their "name" attribute for their pronunciation. MergeRules should continue to get pronunciations.

I'm not understanding how that fits with what I see in the files. If not specified, mapping rule sets the name attribute to `self.__class__.__name__`. Looks like you've gone through and added names manually (or something) to mapping rules with code like: 
```
def get_rule():
    return AcrobatRule, RuleDetails(name="acrobat", executable="acrobat")
```
Furthermore, such names are required-- if I take out the name parameter in the line above I get the message: "AcrobatRule rejected due to detail validation errors: non-ccr types must have 'name'". So seems like at no point do I if the default name attribute of the mapping will which in this case would be "AcrobatRule". That's fine, people just have to know that they need to put in that name parameter, and your message should them that.

**Comment by synkarius** [comment]
Great questions. Here are my thoughts, in the same order as your questions.

Re: "enable all rules", that doesn't really help with the manual testing scenario I mentioned. Here's why. If rules are turned on in the "whitelist" section of rules.toml, they will be loaded (at boot time) and go through all the new safety checks (at boot time). If they're not turned on in the "whitelist" section, they will not be loaded and will not go through the normal safety checks. If rules are turned off in the "whitelist" section and you make a change which breaks one of them, you won't notice in your own manual testing (though the "ModuleTestCase" unit tests may still catch it). Now here's the important part: if rules are turned off in the "whitelist" section, _you cannot enable or disable them without rebooting Dragon_ since they were never loaded. (Loading rules only happens once, at boot, just like in old Caster. I want to emphasize that this is exactly the same as it was before with regards to when rules were loaded. The difference now is that previously loaded rules can get reloaded.) A nice upgrade to my upgrade would be to allow for loading rules after boot time. If that were added (and I don't think it would be terribly difficult, but I don't have the time for it), then your "load all rules" command would do what I think you want it to do. (Note the difference here between "loaded" and "enabled", a difference which didn't exist in the config files in old Caster except in a few very specific cases.)

Your idea about profiles is great and could be implemented with zero code changes (only config changes) using the new "companion rules" feature.

There is not a technical reason for people to not add rules manually to the `_enabled_ordered` list. I only recommend that because the commands for that exist and editing config files is error prone.

You are completely correct about MappingRule pronunciations and `self.__class__.__name__`. All that code I wrote about "_get_best_trigger" and `self.__class__.__name__` was at an earlier stage in the process, before I thought of just rejecting rules outright instead of making a best-effort guess at what their pronunciations should be. I'll delete that "get best trigger" stuff, as it's now useless AND technical debt.
