### ISSUE TITLE
Contextual sticky lists

### ISSUE THREAD

**Issue by chilimangoes** [synkarius/caster#95]
Personally, I find multi-copy and sticky list to be somewhat redundant, and typically only use one or the other (generally multi-copy). I was thinking it might be useful to have multi-copy be global and sticky lists be contextual. You could have multiple sticky list contexts, but (probably) only one active at a time.

The kinds of identifiers and snippets that I store into the multi-copy list tend to mostly be contextual to a particular task that I'm working on. When I switch to coding on caster, for example, it would be convenient to have a list of identifiers and snippets that I was using last time I was working on caster. But I don't need them while I'm coding on one of my work projects.

**Comment by synkarius** [comment]
You make a good point about the functionality overlapping. That exists because one came before the other. The original "copy" command wasn't persistent (or multi-slotted) like multi-copy is, and so the sticky list seemed like a good idea at the time. Now sticky list is almost pointless, and will be completely pointless if a view of multi-copy is implemented.

Contextual multi copy sounds awesome. I can think of two ways to do it, and I think one is clearly better. We could ping the active window like "Auto Command Mode" does, and derive the context from that, or we could allow the user to tag their own contexts manually. I'd vote for the latter for a few reasons:

1. Pinging windows has a delay. You can make the delay small, but that involves pinging more often, and the more you ping, the heavier the pinging gets. I can't use Auto-Mode at work because it freezes Eclipse on our large codebase (and I have use a decent i5).
2. This would make it annoying to carry symbols across editors. Go to other editor, lose context.

**Comment by chilimangoes** [comment]
Yeah, I would definitely prefer setting and switching contexts manually, for exactly the reasons you cited (though, in my experience, pretty much everything makes Eclipse freeze :P). Number 2 is actually the biggest reason for me because it's pretty common that I'll need access to the same set of identifiers across multiple editors when working on a project.

**Comment by synkarius** [comment]
Sadly true about Eclipse. :-(

**Comment by synkarius** [comment]
#154
Sticky List has been cut. If contextual multi-copy is something we want to add, it should get its own new issue.
