### ISSUE TITLE
Customizer UI

### ISSUE THREAD

**Issue by synkarius** [synkarius/caster#99]
* tk-based UI which allows the user to edit/disable/freeze commands from any mapping rule
* user customizations will be saved to a json file, and so not overwritten when the source updates
* customizations include changing specs, the associated actions that go along with them, or the associated extras and the faults that go along with those actions
* user must be able to re-edit customizations in the future

**Comment by synkarius** [comment]
### content

* MappingRule source
* freeze (boolean)
* disable (list of RegisteredAction ids to disable)

**Comment by synkarius** [comment]
Saving the MappingRule directly ensures that the only possible bugs are import errors. There are too many peculiarities with saving individual rules.

**Comment by chilimangoes** [comment]
So for a concrete example, let's use the HTML CCR module. If I understand you correctly, I would be able to disable or modify the specs of any of the individual commands in that module, but would only be able to freeze the *entire* module. Is that correct?

I assume by freeze, you mean that we would basically take a snapshot of the module as it is and use that, rather than future updated versions, until the user unfreezes the module.

For commands that have been customized, is there a way we can notify the user that the official version of that command has changed since they made their customization? This way they can look to see if the new version of the command offers any improvements that they might be interested in.

**Comment by synkarius** [comment]
That's correct, you could only freeze the entire module, and by freeze I mean take a snapshot of the entire module as it is and use that instead of future updated versions.

Also yes, notifying the user like that is a good idea. I think that could be as simple as comparing version numbers or dates etc.

**Comment by synkarius** [comment]
So, I've given this a lot of thought the past few months. Adding filter functions was a good move in and of itself, one which I'm already using, but this whole freezing business increasingly seems like a poor man's substitute for version control, and more of a hassle to both the user and us developers than it's worth. Closing, unless someone can come up with a good argument why freezing should be used instead of version control.

As for the graphical command maker, I'm declaring it outside Caster's scope, in the same way that a GUI builder is outside the scope of Tkinter or an AST visualizer/editor is outside the scope of a given programming language. A graphical command maker would definitely be useful to have, and would lower the bar to entry for many, but it should be its own project.
